version: '3'
services:
  flaskapp:
    build: .
    image: stulplay/justice:latest
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: std_2497_stul
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./home/dev/std-mysql.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:

